# Generated by Django 3.2.6 on 2021-08-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CHSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_file', models.CharField(db_column='src_file', default='', max_length=255)),
                ('src_name', models.CharField(db_column='src_name', default='', max_length=255)),
                ('src_link', models.CharField(db_column='src_link', default='', max_length=255)),
                ('result_text', models.CharField(db_column='result_text', default='', max_length=4096)),
                ('status', models.CharField(db_column='status', default='', max_length=10)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='', max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at')),
            ],
            options={
                'db_table': 'ch_source',
                'managed': False,
            },
        ),
    ]
