# Generated by Django 3.2.6 on 2021-09-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycor', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_django'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_file', models.CharField(db_column='src_file', default='', max_length=255)),
                ('src_name', models.CharField(db_column='src_name', default='', max_length=255)),
                ('src_link', models.CharField(db_column='src_link', default='', max_length=255)),
                ('result_text', models.CharField(db_column='result_text', default='', max_length=4096)),
                ('status', models.CharField(db_column='status', default='', max_length=10)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
                ('create_at', models.DateTimeField(db_column='create_at')),
            ],
            options={
                'db_table': 'ocr_test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CHSource',
        ),
    ]
